source = ~/.config/omarchy/current/theme/hyprlock.conf

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
    ignore_empty_input = true
}

# BACKGROUND
background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# PROFILE_PHOTO
image {
    monitor =
    path = ~/.config/hypr/avatars/chopper-close-avatar.png
    border_size = 2
    border_color = $outer_color
    size = 130
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd =
    position = 0, 40
    halign = center
    valign = center
}

# DAY_MONTH_DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(LC_TIME=pt_BR.UTF-8 date +"%A, %d de %B de %Y" | sed 's/^./\U&/; s/de \(.\)/de \U\1/g')"
    color = $font_color
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = 0, 350
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = $font_color
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    position = 0, 250
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =   JustSpica
    color = $font_color
    font_size = 18
    font_family = SF Pro Display Bold
    position = 0, -56
    halign = center
    valign = center
}

animations {
    enabled = false
}

# INPUT FIELD
input-field {
    monitor =
    size = 500, 60
    position = 0, -164
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 2

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 10
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
