# UI Colors (extended)
accent = "#1C2121"
cursor = "#3c4747"

# Primary colors
foreground = "#3c4747"
background = "#e3d8bc"

# Selection colors
selection_foreground = "#e3d8bc"
selection_background = "#3c4747"

# Normal colors (ANSI 0-7)
color0 = "#e3d8bc"
color1 = "#4F351E"
color2 = "#3A443D"
color3 = "#826e48"
color4 = "#1C2121"
color5 = "#764E27"
color6 = "#7B826D"
color7 = "#121515"

# Bright colors (ANSI 8-15)
color8 = "#b79f70"
color9 = "#966133"
color10 = "#637669"
color11 = "#b59d71"
color12 = "#465353"
color13 = "#c17c38"
color14 = "#a8ae9d"
color15 = "#3c4747"
