-- Generated by nwg-displays on 2026-08-14 at 17:02:32. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@143.85",
    position = "0x0",
    scale = 1
})
