[colors]
[colors.primary]
background = "#171023"
foreground = "#debfe6"

[colors.normal]
black   = "#171023"
red     = "#c591d4"
green   = "#b0b1f4"
yellow  = "#ddb3ed"
blue    = "#9ca1e6"
magenta = "#d99ad8"
cyan    = "#b4b5f7"
white   = "#debfe6"

[colors.bright]
black   = "#5d5378"
red     = "#e8b5fb"
green   = "#c3bfff"
yellow  = "#f2bdff"
blue    = "#c5c7ff"
magenta = "#f4b7f9"
cyan    = "#c6c2ff"
white   = "#f2caff"

[colors.cursor]
text   = "#171023"
cursor = "#debfe6"
