# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#171023"

# Main text color
theme[main_fg]="#debfe6"

# Title color for boxes
theme[title]="#debfe6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#9ca1e6"

# Background color of selected item in processes box
theme[selected_bg]="#debfe6"

# Foreground color of selected item in processes box
theme[selected_fg]="#9ca1e6"

# Color of inactive/disabled text
theme[inactive_fg]="#5d5378"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#e3c9ea"

# Background color of the percentage meters
theme[meter_bg]="#debfe6"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#e3c9ea"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#d99ad8"
theme[mem_box]="#b0b1f4"
theme[net_box]="#c591d4"
theme[proc_box]="#9ca1e6"

# Box divider line and small boxes line color
theme[div_line]="#5d5378"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#b0b1f4"
theme[temp_mid]="#ddb3ed"
theme[temp_end]="#c591d4"

# CPU graph colors (Teal -> Blue -> Purple)
theme[cpu_start]="#b4b5f7"
theme[cpu_mid]="#9ca1e6"
theme[cpu_end]="#d99ad8"

# Mem/Disk free meter
theme[free_start]="#d99ad8"
theme[free_mid]="#9ca1e6"
theme[free_end]="#b4b5f7"

# Mem/Disk cached meter
theme[cached_start]="#9ca1e6"
theme[cached_mid]="#b4b5f7"
theme[cached_end]="#d99ad8"

# Mem/Disk available meter
theme[available_start]="#ddb3ed"
theme[available_mid]="#c591d4"
theme[available_end]="#c591d4"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#b0b1f4"
theme[used_mid]="#b4b5f7"
theme[used_end]="#9ca1e6"

# Download graph colors
theme[download_start]="#ddb3ed"
theme[download_mid]="#c591d4"
theme[download_end]="#c591d4"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#b0b1f4"
theme[upload_mid]="#b4b5f7"
theme[upload_end]="#9ca1e6"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#b4b5f7"
theme[process_mid]="#9ca1e6"
theme[process_end]="#d99ad8"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#171023"
theme[gradient_color_1]="#2e2839"
theme[gradient_color_2]="#debfe6"
theme[gradient_color_3]="#5d5378"
theme[gradient_color_4]="#a78fad"
theme[gradient_color_5]="#debfe6"
theme[gradient_color_6]="#e3c9ea"
theme[gradient_color_7]="#e6cfec"
