# Background and foreground colors
background = #171023
foreground = #debfe6

# Standard colors
palette = 0=#171023
palette = 1=#c591d4
palette = 2=#b0b1f4
palette = 3=#ddb3ed
palette = 4=#9ca1e6
palette = 5=#d99ad8
palette = 6=#b4b5f7
palette = 7=#debfe6

# Bright colors
palette = 8=#5d5378
palette = 9=#e8b5fb
palette = 10=#c3bfff
palette = 11=#f2bdff
palette = 12=#c5c7ff
palette = 13=#f4b7f9
palette = 14=#c6c2ff
palette = 15=#f2caff
